### ISSUE TITLE
What’s the best way to test a plugin’s new npm version?

### ISSUE THREAD

**Issue by Tom-Bonnike** [netlify/plugins#56]
Hi, I see your guidelines state that to update a plugin’s version, we need to have a successful build on Netlify.
That makes sense, but how can I make a build and test it with the new npm version?

I tried pushing the files to my personal website’s repository and used it like so:
```toml
[[plugins]]
  package = './netlify-plugin-inline-critical-css'
```

but it states that it cannot find the `manifest.yml`.

See those deploys:
- https://app.netlify.com/sites/tombonnike/deploys/5ece9676eb53de00061ebe09 (tried without a trailing slash)
- https://app.netlify.com/sites/tombonnike/deploys/5ece963f55c9c201e0d5b59c (with a trailing slash)

I double checked and the manifest is indeed present in the `plugins/netlify-plugin-inline-critical-css` folder: https://github.com/Tom-Bonnike/personal-website. (I tried putting the plugin under a `plugins` directory but it didn’t work either, updated my netlify.toml). See https://app.netlify.com/sites/tombonnike/deploys/5ece99c03ab1430006608bca

---

It would be great to have something like:
```toml
[[plugins]]
  package = 'netlify-plugin-inline-critical-css'
  version = '1.1.0' # Enforce npm version
```

To quickly be able to test plugins.
